[project]
name = "uploader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.6",
    "djangorestframework>=3.16.1",
    "pydantic>=2.11.9",
    "pysocks>=1.7.1",
    "requests>=2.32.5",
]
