# Generated by Django 5.2.1 on 2025-08-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_update', models.BooleanField(default=False)),
                ('update_msg', models.TextField(default='bot is updated !')),
            ],
        ),
    ]
