# Generated by Django 5.2.1 on 2025-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('chat_id', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('link', models.CharField(max_length=70, unique=True)),
                ('other', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
