# Generated by Django 5.2.6 on 2025-09-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_channelsponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_rial', models.PositiveBigIntegerField()),
                ('duration_days', models.IntegerField(help_text='Number of days for the plan. Use a negative value for unlimited.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
