# Generated by Django 5.2.6 on 2025-09-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_session_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='link',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
