# Generated by Django 5.2.6 on 2025-09-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_episode_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
        migrations.AlterField(
            model_name='episode',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
